/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntriesIndexRouteImport } from './routes/entries/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EntriesNewRouteImport } from './routes/entries/new'
import { Route as EntriesIdRouteImport } from './routes/entries/$id'
import { Route as AdminUsersIdStatsRouteImport } from './routes/admin/users/$id/stats'
import { Route as AdminUsersIdEntriesIndexRouteImport } from './routes/admin/users/$id/entries/index'
import { Route as AdminUsersIdEntriesNewRouteImport } from './routes/admin/users/$id/entries/new'
import { Route as AdminUsersIdEntriesEntryIdRouteImport } from './routes/admin/users/$id/entries/$entryId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIndexRoute = EntriesIndexRouteImport.update({
  id: '/entries/',
  path: '/entries/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesNewRoute = EntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdRoute = EntriesIdRouteImport.update({
  id: '/entries/$id',
  path: '/entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdStatsRoute = AdminUsersIdStatsRouteImport.update({
  id: '/admin/users/$id/stats',
  path: '/admin/users/$id/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdEntriesIndexRoute =
  AdminUsersIdEntriesIndexRouteImport.update({
    id: '/admin/users/$id/entries/',
    path: '/admin/users/$id/entries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIdEntriesNewRoute = AdminUsersIdEntriesNewRouteImport.update({
  id: '/admin/users/$id/entries/new',
  path: '/admin/users/$id/entries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdEntriesEntryIdRoute =
  AdminUsersIdEntriesEntryIdRouteImport.update({
    id: '/admin/users/$id/entries/$entryId',
    path: '/admin/users/$id/entries/$entryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/new': typeof EntriesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/entries/': typeof EntriesIndexRoute
  '/admin/users/$id/stats': typeof AdminUsersIdStatsRoute
  '/admin/users/$id/entries/$entryId': typeof AdminUsersIdEntriesEntryIdRoute
  '/admin/users/$id/entries/new': typeof AdminUsersIdEntriesNewRoute
  '/admin/users/$id/entries/': typeof AdminUsersIdEntriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/new': typeof EntriesNewRoute
  '/admin': typeof AdminIndexRoute
  '/entries': typeof EntriesIndexRoute
  '/admin/users/$id/stats': typeof AdminUsersIdStatsRoute
  '/admin/users/$id/entries/$entryId': typeof AdminUsersIdEntriesEntryIdRoute
  '/admin/users/$id/entries/new': typeof AdminUsersIdEntriesNewRoute
  '/admin/users/$id/entries': typeof AdminUsersIdEntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/new': typeof EntriesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/entries/': typeof EntriesIndexRoute
  '/admin/users/$id/stats': typeof AdminUsersIdStatsRoute
  '/admin/users/$id/entries/$entryId': typeof AdminUsersIdEntriesEntryIdRoute
  '/admin/users/$id/entries/new': typeof AdminUsersIdEntriesNewRoute
  '/admin/users/$id/entries/': typeof AdminUsersIdEntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/entries/$id'
    | '/entries/new'
    | '/admin/'
    | '/entries/'
    | '/admin/users/$id/stats'
    | '/admin/users/$id/entries/$entryId'
    | '/admin/users/$id/entries/new'
    | '/admin/users/$id/entries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/entries/$id'
    | '/entries/new'
    | '/admin'
    | '/entries'
    | '/admin/users/$id/stats'
    | '/admin/users/$id/entries/$entryId'
    | '/admin/users/$id/entries/new'
    | '/admin/users/$id/entries'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/entries/$id'
    | '/entries/new'
    | '/admin/'
    | '/entries/'
    | '/admin/users/$id/stats'
    | '/admin/users/$id/entries/$entryId'
    | '/admin/users/$id/entries/new'
    | '/admin/users/$id/entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EntriesIdRoute: typeof EntriesIdRoute
  EntriesNewRoute: typeof EntriesNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EntriesIndexRoute: typeof EntriesIndexRoute
  AdminUsersIdStatsRoute: typeof AdminUsersIdStatsRoute
  AdminUsersIdEntriesEntryIdRoute: typeof AdminUsersIdEntriesEntryIdRoute
  AdminUsersIdEntriesNewRoute: typeof AdminUsersIdEntriesNewRoute
  AdminUsersIdEntriesIndexRoute: typeof AdminUsersIdEntriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/': {
      id: '/entries/'
      path: '/entries'
      fullPath: '/entries/'
      preLoaderRoute: typeof EntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/new': {
      id: '/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof EntriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id': {
      id: '/entries/$id'
      path: '/entries/$id'
      fullPath: '/entries/$id'
      preLoaderRoute: typeof EntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id/stats': {
      id: '/admin/users/$id/stats'
      path: '/admin/users/$id/stats'
      fullPath: '/admin/users/$id/stats'
      preLoaderRoute: typeof AdminUsersIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id/entries/': {
      id: '/admin/users/$id/entries/'
      path: '/admin/users/$id/entries'
      fullPath: '/admin/users/$id/entries/'
      preLoaderRoute: typeof AdminUsersIdEntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id/entries/new': {
      id: '/admin/users/$id/entries/new'
      path: '/admin/users/$id/entries/new'
      fullPath: '/admin/users/$id/entries/new'
      preLoaderRoute: typeof AdminUsersIdEntriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id/entries/$entryId': {
      id: '/admin/users/$id/entries/$entryId'
      path: '/admin/users/$id/entries/$entryId'
      fullPath: '/admin/users/$id/entries/$entryId'
      preLoaderRoute: typeof AdminUsersIdEntriesEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EntriesIdRoute: EntriesIdRoute,
  EntriesNewRoute: EntriesNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  EntriesIndexRoute: EntriesIndexRoute,
  AdminUsersIdStatsRoute: AdminUsersIdStatsRoute,
  AdminUsersIdEntriesEntryIdRoute: AdminUsersIdEntriesEntryIdRoute,
  AdminUsersIdEntriesNewRoute: AdminUsersIdEntriesNewRoute,
  AdminUsersIdEntriesIndexRoute: AdminUsersIdEntriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
